### ISSUE TITLE
Android: requestStoreListing function works not correct

### ISSUE THREAD

**Issue by kaipk** [cranberrygame/cordova-plugin-payment-iap#4]
If i want listen more than 1 product empty Object returned. 

note: one product is a consumable the other a non consumable.

**Works**
<code>var productIds = 'product1';</code>

**Doesnt work**
<code>var productIds = 'product1,product2';</code>

<code>window.iap.requestStoreListing(productIds, function (result) ...</code>

**Comment by ACEEDesign** [comment]
because it should be ['product1','product2']

**Comment by cranberrygame** [comment]
@kaipk 
@ACEEDesign 
Fixed and now following code also works.

var productIds = 'product1,product2';

window.iap.requestStoreListing(productIds, function (result) ...

Thanks
Sang Ki Kwon

**Comment by aesculus** [comment]
This is still an issue with the NPM version. You still need to use the array of products if there is more than one product per @ACEEDesign
